In [1]:
import random
random.randint(50,100)

98

In [2]:
import numpy as np
scores=np.random.randint(50,101,size=(50,5))
scores

array([[ 72,  72,  53,  64,  79],
       [ 59,  91,  50,  59,  82],
       [ 81,  78,  89,  73,  87],
       [ 69,  80,  60,  82,  50],
       [ 59,  88,  79,  72,  59],
       [ 54,  63,  90,  56,  59],
       [ 55,  80,  68,  68,  92],
       [ 67,  55,  70,  53,  59],
       [ 86,  59,  99,  83,  94],
       [ 50,  55,  50,  94,  88],
       [ 58,  97,  92,  80,  64],
       [ 52,  67,  57,  59,  69],
       [ 83,  65,  81,  54,  55],
       [ 75,  62,  85,  69,  60],
       [ 52,  80,  84,  64,  83],
       [ 56,  89,  78,  56,  73],
       [ 92,  60,  54,  57,  78],
       [ 83,  66,  91,  74,  73],
       [ 80,  95,  99,  57,  50],
       [ 54,  94,  94,  74,  94],
       [ 89,  63,  73,  67,  71],
       [ 87,  85,  89,  79,  61],
       [ 78,  50,  93,  78,  60],
       [ 69,  93,  80,  72,  72],
       [ 54, 100,  55, 100,  90],
       [ 67,  93,  69,  68,  67],
       [ 88,  59,  53,  75,  75],
       [ 88,  87,  68,  83,  79],
       [ 63,  54,  54,  96,  65],
       [ 80,  

In [3]:
scores[0]

array([72, 72, 53, 64, 79])

In [4]:
scores[0:3]

array([[72, 72, 53, 64, 79],
       [59, 91, 50, 59, 82],
       [81, 78, 89, 73, 87]])

In [5]:
scores[0:3,0]

array([72, 59, 81])