In [1]:
import numpy as np
scores=np.random.randint(50,101,size=(3,5))
scores

array([[64, 64, 83, 69, 73],
       [58, 60, 86, 94, 61],
       [94, 91, 61, 72, 82]])

In [2]:
np.sum(scores[0])
np.average(scores[0])

70.6

In [3]:
for i in scores:
    print(i)

[64 64 83 69 73]
[58 60 86 94 61]
[94 91 61 72 82]


In [4]:
scores.dtype

dtype('int64')

In [5]:
import pandas as pd
df=pd.DataFrame(data=scores,columns=['國文','英文','數學','地理','歷史'],index=['徐國堂','張xx','王xx'])
df

國文  英文  數學  地理  歷史
徐國堂  64  64  83  69  73
張xx  58  60  86  94  61
王xx  94  91  61  72  82

In [6]:
df.values

array([[64, 64, 83, 69, 73],
       [58, 60, 86, 94, 61],
       [94, 91, 61, 72, 82]])